[channels]
Channel_1 = [ "#005757FF", "#BF0D0DFF" ]
Channel_2 = [ "#FFFF25FF", "#A1A100FF" ]
Channel_3 = [ "#FF9752FF", "#C75000FF" ]
Channel_4 = [ "#50FF50FF", "#00A100FF" ]
Channel_5 = [ "#FF90FFFF", "#D020D0FF" ]
Channel_6 = [ "#A0A0FFFF", "#7777B0FF" ]
Channel_7 = [ "#DEFF25FF", "#8AA100FF" ]
Channel_8 = [ "#FF98A4FF", "#DF0019FF" ]
Channel_9 = [ "#50FFC9FF", "#00A170FF" ]
Channel_10 = [ "#CE8BFFFF", "#A11FFFFF" ]
Channel_11 = [ "#AAAAAAFF", "#6F6F6FFF" ]
Channel_12 = [ "#DDAA77FF", "#996633FF" ]
Channel_13 = [ "#77AADDFF", "#4A6D8FFF" ]
Channel_14 = [ "#AF82D2FF", "#7A4F9AFF" ]
Channel_15 = [ "#A2BB77FF", "#607837FF" ]

[ui]
Text                   = "#e50000ff"
TextDisabled           = "#999999ff"
WindowBg               = "#000000d8"
ChildBg                = "#00000000"
PopupBg                = "#231c1cea"
Border                 = "#7f7f7f7f"
BorderShadow           = "#00000000"
FrameBg                = "#6d6d6d63"
FrameBgHovered         = "#b2686866"
FrameBgActive          = "#bf7a7aaf"
TitleBg                = "#7a2d2da5"
TitleBgActive          = "#841e1edd"
TitleBgCollapsed       = "#cc666633"
MenuBarBg              = "#000000cc"
ScrollbarBg            = "#4c333399"
ScrollbarGrab          = "#f42b2b4c"
ScrollbarGrabHovered   = "#ff111166"
ScrollbarGrabActive    = "#ff5b5b99"
CheckMark              = "#e5e5e57f"
SliderGrab             = "#ffffff4c"
SliderGrabActive       = "#cc636399"
Button                 = "#b52d2d9e"
ButtonHovered          = "#b54444c9"
ButtonActive           = "#cc7575ff"
Header                 = "#8e282872"
HeaderHovered          = "#871c1cff"
HeaderActive           = "#dd8787cc"
Separator              = "#7f7f7f99"
SeparatorHovered       = "#9999b2ff"
SeparatorActive        = "#b2b2e5ff"
ResizeGrip             = "#ffffff19"
ResizeGripHovered      = "#c6d1ff99"
ResizeGripActive       = "#c6d1ffe5"
Tab                    = "#771e1ec9"
TabHovered             = "#ad3535cc"
TabActive              = "#bc4242d6"
TabUnfocused           = "#474791d1"
TabUnfocusedActive     = "#5959a5d6"
DockingPreview         = "#e566664f"
DockingEmptyBg         = "#333333ff"
PlotLines              = "#ffffffff"
PlotLinesHovered       = "#e5b200ff"
PlotHistogram          = "#e5b200ff"
PlotHistogramHovered   = "#ff9900ff"
TableHeaderBg          = "#444460ff"
TableBorderStrong      = "#4f4f72ff"
TableBorderLight       = "#424247ff"
TableRowBg             = "#00000000"
TableRowBgAlt          = "#ffffff11"
TextSelectedBg         = "#ff000059"
DragDropTarget         = "#ffff00e5"
NavHighlight           = "#7272e5cc"
NavWindowingHighlight  = "#ffffffb2"
NavWindowingDimBg      = "#cccccc33"
ModalWindowDimBg       = "#33333359"
PianoKey               = "#202020AA"
PianoKeyAccidental     = "#303030AA"
PianoKeyOctave         = "#b52d2dff"
OctaveRow              = "#b54444c9"
FifthRow               = "#b2686866"