[channels]
Channel_1 = [ "#005757FF", "#BF0D0DFF" ]
Channel_2 = [ "#FFFF25FF", "#A1A100FF" ]
Channel_3 = [ "#FF9752FF", "#C75000FF" ]
Channel_4 = [ "#50FF50FF", "#00A100FF" ]
Channel_5 = [ "#FF90FFFF", "#D020D0FF" ]
Channel_6 = [ "#A0A0FFFF", "#7777B0FF" ]
Channel_7 = [ "#DEFF25FF", "#8AA100FF" ]
Channel_8 = [ "#FF98A4FF", "#DF0019FF" ]
Channel_9 = [ "#50FFC9FF", "#00A170FF" ]
Channel_10 = [ "#CE8BFFFF", "#A11FFFFF" ]
Channel_11 = [ "#AAAAAAFF", "#6F6F6FFF" ]
Channel_12 = [ "#DDAA77FF", "#996633FF" ]
Channel_13 = [ "#77AADDFF", "#4A6D8FFF" ]
Channel_14 = [ "#AF82D2FF", "#7A4F9AFF" ]
Channel_15 = [ "#A2BB77FF", "#607837FF" ]

[ui]
Text                   = [ 0.90, 0.00, 0.00, 1.00 ]
TextDisabled           = [ 0.60, 0.60, 0.60, 1.00 ]
WindowBg               = [ 0.00, 0.00, 0.00, 0.85 ]
ChildBg                = [ 0.00, 0.00, 0.00, 0.00 ]
PopupBg                = [ 0.14, 0.11, 0.11, 0.92 ]
Border                 = [ 0.50, 0.50, 0.50, 0.50 ]
BorderShadow           = [ 0.00, 0.00, 0.00, 0.00 ]
FrameBg                = [ 0.43, 0.43, 0.43, 0.39 ]
FrameBgHovered         = [ 0.70, 0.41, 0.41, 0.40 ]
FrameBgActive          = [ 0.75, 0.48, 0.48, 0.69 ]
TitleBg                = [ 0.48, 0.18, 0.18, 0.65 ]
TitleBgActive          = [ 0.52, 0.12, 0.12, 0.87 ]
TitleBgCollapsed       = [ 0.80, 0.40, 0.40, 0.20 ]
MenuBarBg              = [ 0.00, 0.00, 0.00, 0.80 ]
ScrollbarBg            = [ 0.30, 0.20, 0.20, 0.60 ]
ScrollbarGrab          = [ 0.96, 0.17, 0.17, 0.30 ]
ScrollbarGrabHovered   = [ 1.00, 0.07, 0.07, 0.40 ]
ScrollbarGrabActive    = [ 1.00, 0.36, 0.36, 0.60 ]
CheckMark              = [ 0.90, 0.90, 0.90, 0.50 ]
SliderGrab             = [ 1.00, 1.00, 1.00, 0.30 ]
SliderGrabActive       = [ 0.80, 0.39, 0.39, 0.60 ]
Button                 = [ 0.71, 0.18, 0.18, 0.62 ]
ButtonHovered          = [ 0.71, 0.27, 0.27, 0.79 ]
ButtonActive           = [ 0.80, 0.46, 0.46, 1.00 ]
Header                 = [ 0.56, 0.16, 0.16, 0.45 ]
HeaderHovered          = [ 0.53, 0.11, 0.11, 1.00 ]
HeaderActive           = [ 0.87, 0.53, 0.53, 0.80 ]
Separator              = [ 0.50, 0.50, 0.50, 0.60 ]
SeparatorHovered       = [ 0.60, 0.60, 0.70, 1.00 ]
SeparatorActive        = [ 0.70, 0.70, 0.90, 1.00 ]
ResizeGrip             = [ 1.00, 1.00, 1.00, 0.10 ]
ResizeGripHovered      = [ 0.78, 0.82, 1.00, 0.60 ]
ResizeGripActive       = [ 0.78, 0.82, 1.00, 0.90 ]
Tab                    = [ 0.47, 0.12, 0.12, 0.79 ]
TabHovered             = [ 0.68, 0.21, 0.21, 0.80 ]
TabActive              = [ 0.74, 0.26, 0.26, 0.84 ]
TabUnfocused           = [ 0.28, 0.28, 0.57, 0.82 ]
TabUnfocusedActive     = [ 0.35, 0.35, 0.65, 0.84 ]
DockingPreview         = [ 0.90, 0.40, 0.40, 0.31 ]
DockingEmptyBg         = [ 0.20, 0.20, 0.20, 1.00 ]
PlotLines              = [ 1.00, 1.00, 1.00, 1.00 ]
PlotLinesHovered       = [ 0.90, 0.70, 0.00, 1.00 ]
PlotHistogram          = [ 0.90, 0.70, 0.00, 1.00 ]
PlotHistogramHovered   = [ 1.00, 0.60, 0.00, 1.00 ]
TableHeaderBg          = [ 0.27, 0.27, 0.38, 1.00 ]
TableBorderStrong      = [ 0.31, 0.31, 0.45, 1.00 ]
TableBorderLight       = [ 0.26, 0.26, 0.28, 1.00 ]
TableRowBg             = [ 0.00, 0.00, 0.00, 0.00 ]
TableRowBgAlt          = [ 1.00, 1.00, 1.00, 0.07 ]
TextSelectedBg         = [ 1.00, 0.00, 0.00, 0.35 ]
DragDropTarget         = [ 1.00, 1.00, 0.00, 0.90 ]
NavHighlight           = [ 0.45, 0.45, 0.90, 0.80 ]
NavWindowingHighlight  = [ 1.00, 1.00, 1.00, 0.70 ]
NavWindowingDimBg      = [ 0.80, 0.80, 0.80, 0.20 ]
ModalWindowDimBg       = [ 0.20, 0.20, 0.20, 0.35 ]
PianoKey               = "#202020AA"
PianoKeyAccidental     = "#303030AA"
PianoKeyOctave         = [ 0.71, 0.18, 0.18, 1.00 ]
OctaveRow              = [ 0.71, 0.27, 0.27, 0.79 ]
FifthRow               = [ 0.70, 0.41, 0.41, 0.40 ]